debug: true
server:
  web_socket:
    addr: 0.0.0.0:80
data:
  database:
    driver: "mysql"
    connection: "vroomdb:HitryVRoom123@tcp(mysql:3306)/wstest?charset=utf8&parseTime=true"
    conn_max_life_time: 1000
    max_open_conn: 10
    max_idle_conn: 10
