debug: true
server:
  web_socket:
    addr: 0.0.0.0:8088
data:
  database:
    driver: "mysql"
    connection: "vroomdb:HitryVRoom123@tcp(10.35.149.21:30006)/lifue_test?charset=utf8&parseTime=true"
    conn_max_life_time: 1000
    max_open_conn: 10
    max_idle_conn: 10
